name: My First GitHub Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Introduction
        run: echo "Hello! My name is Waqar Ali."

      - name: Goal
        run: echo "I want to become an AI Engineer."

      - name: Learning
        run: echo "Today I learned GitHub Actions!"