name: Manual Workflow Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello Waqar!"

      - name: Show Date
        run: date

      - name: Show Current Folder
        run: pwd