name: My Code

on:
  push:

jobs: 
  code:
    runs-on: ubuntu-latest

    steps:
      - name: my first code
        run: echo "Welcome to my first code"
      
      - name: my 2nd code
        run: echo "Welcome to my 2nd code"
      
      - name: my 3rd code
        run: echo "Welcome to my 4th code"