name: My Code

on:
  push:

jobs: 
  codes:
    runs-on: ubuntu-latest

    steps:
      - name: my first code
        run: Welcome to my first code
      
      - name: my 2nd code
        run: Welcome to my 2nd code
      
      - name: my 3rd code
        run: Welcome to my 4th code