name: My Practice Workflow

on:
  push:

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Greeting
        run: echo "Hello GitHub!"

      - name: Learning
        run: echo "I am learning GitHub Actions."

      - name: Future
        run: echo "One day I will automate my MERN projects."